/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import javax.swing.JOptionPane;

/**
 *
 * @author marccio
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        botonDesconectar.setEnabled(false);
        areaChat.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaChat = new javax.swing.JTextArea();
        fieldInput = new javax.swing.JTextField();
        fieldHost = new javax.swing.JTextField();
        fieldApodo = new javax.swing.JTextField();
        fieldPort = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonDesconectar = new javax.swing.JButton();
        botonConectar = new javax.swing.JButton();
        iconoStatus = new javax.swing.JPanel();
        labelStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        areaChat.setColumns(20);
        areaChat.setRows(5);
        jScrollPane1.setViewportView(areaChat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 437, 622));

        fieldInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldInputKeyReleased(evt);
            }
        });
        getContentPane().add(fieldInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 680, 437, -1));

        fieldHost.setText("localhost");
        fieldHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHostActionPerformed(evt);
            }
        });
        getContentPane().add(fieldHost, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 78, 186, -1));

        fieldApodo.setText("pepito");
        getContentPane().add(fieldApodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 363, 186, -1));

        fieldPort.setText("54321");
        getContentPane().add(fieldPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 221, 186, -1));

        jLabel1.setText("Host IP:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 83, -1, -1));

        jLabel2.setText("Port:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 226, -1, -1));

        jLabel3.setText("Apodo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 368, -1, -1));

        botonDesconectar.setText("Disconnect");
        getContentPane().add(botonDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 483, 185, 134));

        botonConectar.setText("Connect");
        botonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConectarActionPerformed(evt);
            }
        });
        getContentPane().add(botonConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 483, 185, 134));

        iconoStatus.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout iconoStatusLayout = new javax.swing.GroupLayout(iconoStatus);
        iconoStatus.setLayout(iconoStatusLayout);
        iconoStatusLayout.setHorizontalGroup(
            iconoStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        iconoStatusLayout.setVerticalGroup(
            iconoStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(iconoStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, -1, -1));

        labelStatus.setText("Desconectado");
        getContentPane().add(labelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 715, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldInputKeyReleased
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            System.out.println("Tocaste ENTER");
            fieldInput.setText("");
        }
    }//GEN-LAST:event_fieldInputKeyReleased

    private void botonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConectarActionPerformed
        //mando un paquete UDP con mi apodo para registrarme en el servidor
        if (fieldHost.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese la IP del Host", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (fieldPort.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese un número de Puerto", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (fieldApodo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese un Apodo", "Error", JOptionPane.ERROR_MESSAGE);
        } else { //hay datos en todos los campos
            try {
                DatagramSocket clientSocket = new DatagramSocket();
                InetAddress IPAddress = InetAddress.getByName(fieldHost.getText());
                byte[] sendData = new byte[1024];
                byte[] receiveData = new byte[1024];
                String mensajeAEnviar = "LOGIN <" + fieldApodo.getText() + "><CR>";
                sendData = mensajeAEnviar.getBytes();
                // creo paquete de envío y lo envío
                DatagramPacket sendPacket = new DatagramPacket(sendData, sendData.length, IPAddress,
                        Integer.parseInt(fieldPort.getText()));
                clientSocket.send(sendPacket);
                // creo paquete de recepción y lo recibo (con timeout de 5 segundos)
                DatagramPacket receivePacket = new DatagramPacket(receiveData, receiveData.length);
                clientSocket.setSoTimeout(5000);
                clientSocket.receive(receivePacket);
                //actualizo ventana de chat
                String mensaje = new String(receivePacket.getData());
                String ventanaChat = areaChat.getText();
                ventanaChat = ventanaChat.concat("\n" + mensaje);
                areaChat.setText(ventanaChat);
                System.out.println(mensaje); // consola
                //cierro socket
                clientSocket.close();
                botonConectar.setEnabled(false);
                botonDesconectar.setEnabled(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "No se pudo realizar la conexión \n" + "Motivo: " + e.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
                System.out.println(e.getCause().toString());
            }
        }

    }//GEN-LAST:event_botonConectarActionPerformed

    private void fieldHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaChat;
    private javax.swing.JButton botonConectar;
    private javax.swing.JButton botonDesconectar;
    private javax.swing.JTextField fieldApodo;
    private javax.swing.JTextField fieldHost;
    private javax.swing.JTextField fieldInput;
    private javax.swing.JTextField fieldPort;
    private javax.swing.JPanel iconoStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelStatus;
    // End of variables declaration//GEN-END:variables
}
