/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

/**
 *
 * @author marccio
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaChat = new javax.swing.JTextArea();
        fieldInput = new javax.swing.JTextField();
        fieldHost = new javax.swing.JTextField();
        fieldApodo = new javax.swing.JTextField();
        fieldPort = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonDesconectar = new javax.swing.JButton();
        botonConectar = new javax.swing.JButton();
        iconoStatus = new javax.swing.JPanel();
        labelStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        areaChat.setColumns(20);
        areaChat.setRows(5);
        jScrollPane1.setViewportView(areaChat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 437, 622));
        getContentPane().add(fieldInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 680, 437, -1));
        getContentPane().add(fieldHost, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 78, 186, -1));
        getContentPane().add(fieldApodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 363, 186, -1));
        getContentPane().add(fieldPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 221, 186, -1));

        jLabel1.setText("Host IP:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 83, -1, -1));

        jLabel2.setText("Port:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 226, -1, -1));

        jLabel3.setText("Apodo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 368, -1, -1));

        botonDesconectar.setText("Disconnect");
        getContentPane().add(botonDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 483, 185, 134));

        botonConectar.setText("Connect");
        getContentPane().add(botonConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 483, 185, 134));

        iconoStatus.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout iconoStatusLayout = new javax.swing.GroupLayout(iconoStatus);
        iconoStatus.setLayout(iconoStatusLayout);
        iconoStatusLayout.setHorizontalGroup(
            iconoStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        iconoStatusLayout.setVerticalGroup(
            iconoStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(iconoStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, -1, -1));

        labelStatus.setText("Desconectado");
        getContentPane().add(labelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 715, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaChat;
    private javax.swing.JButton botonConectar;
    private javax.swing.JButton botonDesconectar;
    private javax.swing.JTextField fieldApodo;
    private javax.swing.JTextField fieldHost;
    private javax.swing.JTextField fieldInput;
    private javax.swing.JTextField fieldPort;
    private javax.swing.JPanel iconoStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelStatus;
    // End of variables declaration//GEN-END:variables
}
